### ISSUE TITLE
New processes are given events that happened before they were started

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/Radium#8] opened 2016-02-09 15:12 UTC
When a process is created while events are being distributed (i. e. Running a program in besh) the distribute loop may distribute events to them that occurred before they were started. For example, when running the `lua` program, occasionally it will receive the newline key event from pressing enter to run the command in besh. This should not happen as the process had not been created yet when the event was received.

**Comment by Lignumm** [comment] 2016-02-09 16:20
Ah, I remember having this problem in cheetOS. I'll try to find the fix for it in its source.

**Comment by Lignumm** [comment] 2016-02-09 16:28
Alright, I couldn't reproduce the issue but it should be fixed as of d4c5671bdb7524b37ca263a1c8e0d95742dcf000. Reopen if it happens again.

**Closed by Lignumm** 2016-02-09 16:28 UTC

**Comment by apemanzilla** [comment] 2016-02-09 19:07
Seems to be fixed now.

**Comment by Lignumm** [comment] 2016-02-09 19:11
Awesome.
